### ISSUE TITLE
How to add Menu View Controller should be on top of navigation bar?

### ISSUE THREAD

**Issue by SusheelYadav455** [ashishkakkad8/AKSwiftSlideMenu#22]
Hi i want to add menu view controller should be on top of navigation bar, not below of navigation bar..please suggest me the updated code..

**Comment by jeremiasdsa** [comment]
Hi @ashishkakkad8,

Is that possible to make MenuViewController on top of navigationBar ?

**Comment by jeremiasdsa** [comment]
I found a solution on close issues @SusheelYadavAhex. 

here is what you need to do: 

change this line self.view.addSubview(menuVC.view) to
UIApplication.shared.delegate.window?.addSubview(menuVC.view)

**Comment by ThripthiHaridas** [comment]
I added the above code but menu view controller doesn't appear on top of navigation bar. Please help

**Comment by ashishkakkad8** [comment]
This functionality is not done with this code.

**Comment by jeremiasdsa** [comment]
Hi, @ThripthiHaridas 
 
<img width="412" alt="screen shot 2018-10-10 at 21 44 34" src="https://user-images.githubusercontent.com/9071775/46773848-e95bad80-ccd5-11e8-8d82-2d6619baa7aa.png">

Is that what u'r looking for?

**Comment by dilipiOSDeveloper** [comment]
> Hi, @ThripthiHaridas
> 
> <img alt="screen shot 2018-10-10 at 21 44 34" width="412" src="https://user-images.githubusercontent.com/9071775/46773848-e95bad80-ccd5-11e8-8d82-2d6619baa7aa.png">
> 
> Is that what u'r looking for?

can u tell me how u resolved this issue
