### ISSUE TITLE
Errors in BaseViewController Class

### ISSUE THREAD

**Issue by damilolah** [ashishkakkad8/AKSwiftSlideMenu#3]
Expected expression in list of expressions on this line:

  btnShowMenu.addTarget(self, action: #selector(BaseViewController.onSlideMenuButtonPressed(_:)), forControlEvents: UIControlEvents.TouchUpInside)

**Comment by damilolah** [comment]
Never mind... Thanks

**Comment by ashishkakkad8** [comment]
You have to update to Xcode 7.3. It's code of Swift 2.2
