### ISSUE TITLE
SwiftUI Support - Hacktoberfest

### ISSUE THREAD

**Issue by ashishkakkad8** [ashishkakkad8/AKSwiftSlideMenu#30]

**Comment by narendrajagne** [comment]
Hi Can you assign me this issue ?

**Comment by aniket-singh-01** [comment]
hi , please assign this to me. And whatever is the issue , i will try to solve.

**Comment by IamAbdulQadar** [comment]
I am not the owner.

Regards,
*Abdul Qadar*
iOS Engineer
+92 300 0816994 <+923246003005> *|* LinkedIn Profile
<https://www.linkedin.com/in/iamabdulqadar/>

**Comment by ashishkakkad8** [comment]
@narendrajagne @aniket-singh-01 Assigned to both of you.

**Comment by aniket-singh-01** [comment]
what is the issue? or can you explain what to do.
