### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by nsleche** [ashishkakkad8/AKSwiftSlideMenu#6]
It's a really cool library, it'd be nice to have Cocoapods support, i think [this list](https://github.com/thellimist/EZPods) and [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) can help you.

**Comment by amitg02** [comment]
Add Left/Right Swipe Gesture in this .

**Comment by ghost** [comment]
I agree.

**Comment by ashishkakkad8** [comment]
I will try to have Cocoapods support with this library. Thank you for suggestions.

**Comment by ghost** [comment]
Thanks!
